# Generated by Django 4.2.16 on 2025-07-01 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dimensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100, unique=True, verbose_name='Габариты')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Материал')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=100, unique=True, verbose_name='Артикул')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('stock', models.IntegerField(verbose_name='Остаток')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('main_photo', models.ImageField(upload_to='products/main/', verbose_name='Главное фото')),
                ('additional_photo1', models.ImageField(upload_to='products/additional/', verbose_name='Доп. фото №1')),
                ('additional_photo2', models.ImageField(upload_to='products/additional/', verbose_name='Доп. фото №2')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.material')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.product')),
            ],
            options={
                'unique_together': {('product', 'material')},
            },
        ),
        migrations.CreateModel(
            name='ProductDimensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.dimensions')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.product')),
            ],
            options={
                'unique_together': {('product', 'dimensions')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.ManyToManyField(through='offer.ProductDimensions', to='offer.dimensions', verbose_name='Габариты'),
        ),
        migrations.AddField(
            model_name='product',
            name='materials',
            field=models.ManyToManyField(through='offer.ProductMaterial', to='offer.material', verbose_name='Материалы'),
        ),
    ]
