# Generated by Django 4.2.16 on 2025-06-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('material', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('dimensions', models.CharField(max_length=100)),
                ('main_photo', models.ImageField(upload_to='products/main/')),
                ('additional_photo1', models.ImageField(upload_to='products/additional/')),
                ('additional_photo2', models.ImageField(upload_to='products/additional/')),
                ('materials', models.TextField()),
                ('sizes', models.TextField()),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
