# Generated by Django 4.2.16 on 2025-07-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dimensions',
            options={'verbose_name': 'Размер', 'verbose_name_plural': 'Размеры'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Материал', 'verbose_name_plural': 'Материалы'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='product',
            name='dimensions',
            field=models.ManyToManyField(blank=True, null=True, through='offer.ProductDimensions', to='offer.dimensions', verbose_name='Габариты'),
        ),
        migrations.AlterField(
            model_name='product',
            name='materials',
            field=models.ManyToManyField(blank=True, null=True, through='offer.ProductMaterial', to='offer.material', verbose_name='Материалы'),
        ),
    ]
