# Generated by Django 4.2.16 on 2025-06-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='materials',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.AlterField(
            model_name='product',
            name='additional_photo1',
            field=models.ImageField(upload_to='products/additional/', verbose_name='Доп. фото №1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='additional_photo2',
            field=models.ImageField(upload_to='products/additional/', verbose_name='Доп. фото №2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(max_length=100, unique=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(max_length=50, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimensions',
            field=models.CharField(max_length=100, verbose_name='Габариты'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_photo',
            field=models.ImageField(upload_to='products/main/', verbose_name='Главное фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(max_length=100, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(verbose_name='Остаток'),
        ),
    ]
