# Generated by Django 4.2.16 on 2025-07-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_alter_dimensions_options_alter_material_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimensions',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='dimensions',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Габариты'),
        ),
    ]
