# Generated by Django 4.2.16 on 2025-06-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_remove_product_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='product_pdfs/', verbose_name='PDF файл'),
        ),
    ]
